language: php

php:
  - 5.5
  - 5.4
  - 5.3

env:
  - JUST_INSTALL=1
  - SKIP_UPGRADE_TESTS=1

matrix:
    exclude:
        - php: 5.5
          env: JUST_INSTALL=1
        - php: 5.3
          env: JUST_INSTALL=1 

before_script: extras/dev/travis/before.sh

<<<<<<< HEAD
script: php tests/all_tests.php
=======
script: php tests/all_unit_tests.php
>>>>>>> 69c457d591ebcd4950f0be0111bae106cf1ac0ea
